[package]
name = "aoc_rust"
version = "0.1.0"
authors = ["Jesper Eskilson <jesper.eskilson@klarna.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
