name: erlang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: erlang:22.0.7

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: "cd aoc_erlang && rebar3 compile"
    - name: XRef
      run: "cd aoc_erlang && rebar3 xref"
    #- name: Dialyzer
    #  run: "cd aoc_erlang && rebar3 dialyzer"
    - name: Run solutions (2015)
      run: "cd aoc_erlang && rebar3 ct --suite aoc2015_SUITE -v"
    - name: Run solutions (2016)
      run: "cd aoc_erlang && rebar3 ct --suite aoc2016_SUITE -v"
    - name: Run solutions (2017)
      run: "cd aoc_erlang && rebar3 ct --suite aoc2017_SUITE -v"
    - name: Run solutions (2018)
      run: "cd aoc_erlang && rebar3 ct --suite aoc2018_SUITE -v"
    - name: Run solutions (2019)
      run: "cd aoc_erlang && rebar3 ct --suite aoc2019_SUITE -v"
    - name: Run solutions (2020)
      run: "cd aoc_erlang && rebar3 ct --suite aoc2020_SUITE -v"
