name: erlang

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    name: OTP ${{ matrix.otp }}
    matrix:
      otp: ["23.1", "24.0"]

    container:
      image: erlang:${{ matrix.otp }}

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: "cd aoc_erlang && rebar3 compile"
    - name: XRef
      run: "cd aoc_erlang && rebar3 xref"
    - name: Dialyzer
      run: "cd aoc_erlang && rebar3 dialyzer"
    - name: Solve puzzles
      run: "cd aoc_erlang && rebar3 eunit -m aoc_eunit"
    - name: Find unused code
      run: "cd aoc_erlang && rebar3 hank"
